"""
One-time (or on-demand) script to build config/select_by.yaml.

Scans every .doc / .docx file under Client Profiles/, extracts the
SELECT BY value, and maps it to the db_code found in the filename.

db_code is detected by these patterns (in order):
  1. Leading code before a dash/space:  "N67D - NCAF..."  → N67D
  2. Code in parentheses:               "Father Bills (F51D)" → F51D
  3. Code at end of stem:               "NATK - NATCAK-KIDS (X06)" → X06

Run from the project root:
    python build_select_by_yaml.py

Re-run any time new profile files are added.
"""

import re
import glob
import logging
from pathlib import Path

import yaml

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)

_ROOT      = Path(__file__).parent
_PROFILES  = _ROOT / "Client Profiles"
_OUT_YAML  = _ROOT / "config" / "select_by.yaml"

# Matches codes like N67D, A40, X06, F51D, M41, C90D etc.
_CODE_RE   = re.compile(r"\b([A-Z]\d+[A-Z]?)\b")
_SELECT_RE = re.compile(
    r"SELECT BY[:\s]+(.+?)(?:\s{3,}|STANDARD\s+SUP|FILE\s+UPDATED|\*\*|\n|$)",
    re.IGNORECASE,
)


def _extract_select_by(path: Path) -> str:
    suffix = path.suffix.lower()
    try:
        if suffix == ".docx":
            from docx import Document
            doc = Document(str(path))
            full_text = "\n".join(p.text for p in doc.paragraphs)
        elif suffix == ".doc":
            with open(path, "rb") as fh:
                raw = fh.read()
            full_text = "".join(
                ch if 32 <= ord(ch) < 128 else " "
                for ch in raw.decode("latin-1", errors="replace")
            )
        else:
            return ""
    except Exception as exc:
        log.warning("Cannot read %s: %s", path.name, exc)
        return ""

    m = _SELECT_RE.search(full_text)
    if not m:
        return ""
    value = m.group(1).strip()
    # Strip Word mail-merge field placeholder
    mf = re.match(r'MERGEFIELD\s+"?SELECT_BY"?\s+(.*)', value, re.IGNORECASE)
    if mf:
        value = mf.group(1).strip()
    return value


def _extract_db_code(stem: str) -> str:
    """
    Try to pull a db_code from a filename stem.
    Prefer codes with a letter suffix (N67D over N67).
    """
    # 1. Leading code: "N67D - NCAF..."
    m = re.match(r"^([A-Z]\d+[A-Z]?)\s*[-\s]", stem)
    if m:
        return m.group(1)

    # 2. Code in parentheses — prefer longer/suffixed
    in_parens = re.findall(r"\(([A-Z]\d+[A-Z]?)\)", stem)
    if in_parens:
        # prefer codes with a letter suffix (e.g. F51D over N67)
        suffixed = [c for c in in_parens if re.match(r"[A-Z]\d+[A-Z]$", c)]
        return suffixed[0] if suffixed else in_parens[0]

    # 3. Any code anywhere in stem
    codes = _CODE_RE.findall(stem)
    if codes:
        suffixed = [c for c in codes if re.match(r"[A-Z]\d+[A-Z]$", c)]
        return suffixed[0] if suffixed else codes[0]

    return ""


def build():
    if not _PROFILES.is_dir():
        log.error("Client Profiles directory not found: %s", _PROFILES)
        return

    files = [
        f for f in _PROFILES.rglob("*")
        if f.is_file()
        and not f.name.startswith("~")
        and f.suffix.lower() in (".doc", ".docx")
    ]
    log.info("Found %d profile files", len(files))

    mapping: dict[str, str] = {}
    skipped_no_code   = []
    skipped_no_select = []

    for path in sorted(files):
        stem = path.stem.upper()
        db_code = _extract_db_code(stem)
        if not db_code:
            skipped_no_code.append(path.name)
            continue

        select_by = _extract_select_by(path)
        if not select_by:
            skipped_no_select.append(path.name)
            continue

        # Prefer the first value seen (active profiles win over OLD PROFILES)
        if db_code not in mapping:
            mapping[db_code] = select_by
            log.info("  %-10s → %s  [%s]", db_code, select_by, path.name)
        else:
            if mapping[db_code] != select_by:
                log.debug("  %-10s already mapped (%s); ignoring %s",
                          db_code, mapping[db_code], path.name)

    # Write YAML
    _OUT_YAML.parent.mkdir(exist_ok=True)
    with open(_OUT_YAML, "w", encoding="utf-8") as fh:
        fh.write("# db_code → SELECT BY value\n")
        fh.write("# Auto-generated by build_select_by_yaml.py — re-run when profiles change.\n\n")
        for code, val in sorted(mapping.items()):
            fh.write(f"{code}: {val!r}\n")

    log.info("\nWrote %d entries to %s", len(mapping), _OUT_YAML)
    if skipped_no_code:
        log.info("Skipped (no db_code in filename): %d files", len(skipped_no_code))
    if skipped_no_select:
        log.info("Skipped (no SELECT BY in file):   %d files", len(skipped_no_select))


if __name__ == "__main__":
    build()
