- db_code: S42D
  billing_cust: S42
  db_name: SACRED HEART SOUTHERN MISSIONS
  rental_name: SACRED HEART AUTO LEAGUE
  abbrev: SHSMAL
  list_manager: DATA-AXLE
  lm_contact: MAYURI
  lrr: null
  comments: null
- db_code: S42D
  billing_cust: S42
  db_name: SACRED HEART SOUTHERN MISSIONS
  rental_name: SACRED HEART LIFE TRENDS
  abbrev: SHSMLT
  list_manager: DATA-AXLE
  lm_contact: MAYURI
  lrr: null
  comments: null
- db_code: S42D
  billing_cust: S42
  db_name: SACRED HEART SOUTHERN MISSIONS
  rental_name: SACRED HEART MASS CARD
  abbrev: SHSMMC
  list_manager: DATA-AXLE
  lm_contact: MAYURI
  lrr: null
  comments: null
- db_code: S42D
  billing_cust: S42
  db_name: SACRED HEART SOUTHERN MISSIONS
  rental_name: SACRED HEART MASTERFILE
  abbrev: SHSMMF
  list_manager: DATA-AXLE
  lm_contact: MAYURI
  lrr: null
  comments: null
- db_code: S42D
  billing_cust: S42
  db_name: SACRED HEART SOUTHERN MISSIONS
  rental_name: SACRED HEART SOUTHERN MISSIONS
  abbrev: SHSM
  list_manager: DATA-AXLE
  lm_contact: MAYURI
  lrr: null
  comments: null
- db_code: S42D
  billing_cust: S42
  db_name: SACRED HEART SOUTHERN MISSIONS
  rental_name: SACRED HEART SOUTHERN MISSIONS SPANISH DNRS
  abbrev: SHSMSP
  list_manager: DATA-AXLE
  lm_contact: MAYURI
  lrr: null
  comments: null
- db_code: F51D
  billing_cust: F51
  db_name: FATHER BILL'S
  rental_name: FATHER BILL'S MAINSPRING
  abbrev: null
  list_manager: DATA-AXLE
  lm_contact: null
  lrr: AWD
  comments: TOLD WHEN TO UPDATE
- db_code: I18D
  billing_cust: I18
  db_name: INTL EYE FOUNDATION
  rental_name: INTL EYE FOUNDATION
  abbrev: null
  list_manager: DATA-AXLE
  lm_contact: null
  lrr: AWD
  comments: carried over - not in 2026 sheet
- db_code: M47R
  billing_cust: M48
  db_name: MVLA & MVLA HIGH DOLLAR
  rental_name: MOUNT VERNON LADIES ASSOCIATION
  abbrev: null
  list_manager: DATA-AXLE
  lm_contact: null
  lrr: AWD
  comments: carried over - not in 2026 sheet
- db_code: N48A
  billing_cust: N48
  db_name: THE NATIONAL SHRINE
  rental_name: BASILICA;NATL SHRINE;IMMACULATE CONCEPTION
  abbrev: null
  list_manager: DATA-AXLE
  lm_contact: CARMEN
  lrr: JRH
  comments: carried over - not in 2026 sheet
