- db_code: T11R
  billing_cust: T11
  db_name: TVC LIST RENTAL ACC
  rental_name: ALLIANCE OF CONSERVATIVE CATHOLIC DONORS
  list_manager: MARY E GRANGER
  lm_contact: ADAM
  lrr: AWD
  comments: null
