- db_code: N85A
  billing_cust: N85
  db_name: NHES
  rental_name: NATL HUMANE EDU SOCIETY
  list_manager: NITN
  lm_contact: CHERYL/JEN
  lrr: AWD
  comments: null
- db_code: P12D
  billing_cust: P24
  db_name: PREVENT BLINDNESS
  rental_name: PREVENT BLINDNESS
  list_manager: NITN
  lm_contact: CHERYL/JEN
  lrr: AWD
  comments: WHEN REQUESTED
